### ISSUE TITLE
Where is the game

### ISSUE THREAD

**Issue by godlyshadow** [deannreid/TWD_Server_Missions#76]
Daisy Launcher has updated, Can't find [VL] anywhere on its server menu is there a new name

**Comment by VLHosting** [comment]
Don't have DayZ Launcher installed atm, but if you can manually enter an IP, use:
vl1.voxelloop.co.uk:2302

**Comment by deannreid** [comment]
Yeah, DZ Launcher is broken at the moment, gonna shout at the guy when he is on Skype next :)

**Comment by deannreid** [comment]
Fixed Server Now in the latest DayZ Launcher
