### ISSUE TITLE
locked vehicles

### ISSUE THREAD

**Issue by Duuks** [deannreid/TWD_Server_Missions#99]
the map is starting to get filled with locked vehicles. any way to have them unlock and then delete after a certain amount of time?
10days locked vehicle doesnt move, its unclocked
3 days after it has been unlocked and still hasn't moved it is deleted

somethign like that?

**Comment by deannreid** [comment]
Merged #97

**Comment by deannreid** [comment]
Added SQL Statement to unlock vehicles after 2 weeks and to delete them after 3 weeks if still no update to position.
